# SPDX-License-Identifier: GPL-2.0
#
# Dynamic-loader kselftest. No binary to build -
# uses the host's /bin/dash via hostfs to exercise ld-linux
# in-guest and cover first-instruction fetch on shared-library pages.

TEST_PROGS := run-dyn-loader.sh

include ../../lib.mk
